module.exports = {
  '@&': { name: 'jsapp', parser: 'array', default: [], merge: true },
  '++': { name: 'wrappers', parser: 'auxstring', default: {}, merge: true },
  '>+': { name: 'wrapperbody', parser: 'html', default: '', merge: true },
  '><': { name: 'body', parser: 'html', default: '', merge: true },
  '@>': { name: 'jsheader', parser: 'string', default: '', merge: true },
  '@@': { name: 'js', parser: 'string', default: '', merge: true },
  '@<': { name: 'jsfooter', parser: 'string', default: '', merge: true },
  '>@': { name: 'wrapperjs', parser: 'string', default: '', merge: true },
  '##': { name: 'css', parser: 'string', default: '', merge: true },
  '""': { name: 'documentation', parser: 'string', default: '' },
  '--': { name: 'modules', parser: 'object', default: [], merge: true },
  '==': { name: 'pixel', parser: 'string', default: '', merge: true },
  '>>': { name: 'header', parser: 'html', default: '', merge: true },
  '<<': { name: 'footer', parser: 'html', default: '', merge: true },
  '<>': { name: 'scripts', parser: 'html', default: '', merge: true },
  '#>': { name: 'cssheader', parser: 'string', default: '', merge: true },
  '##': { name: 'css', parser: 'string', default: '', merge: true },
  '#<': { name: 'cssfooter', parser: 'string', default: '', merge: true },
  '>#': { name: 'wrappercss', parser: 'string', default: '', merge: true },
  '|@': { name: 'jstests', parser: 'string', default: '', merge: true },
  '||': { name: 'assert', parser: 'string', default: '', merge: true },
  '&>': { name: 'appheader', parser: 'array', default: [], merge: true },
  '&&': { name: 'app', parser: 'array', default: [], merge: true },
  '&<': { name: 'appfooter', parser: 'array', default: [], merge: true },
  '|&': { name: 'apptests', parser: 'array', default: [], merge: true },
  '%%': { name: 'macros', parser: 'auxstring', default: {}, merge: true },
  '**': { name: 'devops', parser: 'auxstring', default: [], merge: true }
};
